### ISSUE TITLE
Use ns[1-5] to verify changes

### ISSUE THREAD

**Issue by nreilly** [IdeaSynthesis/letsencrypt-dns01-hooks#3]
In a split DNS configuration, looking up changes made in Linode DNS will never appear in the local DNS. Is it possible to have this tool check if the TXT records are published by querying the master name servers ns[1-5].linode.com directly?

**Comment by fomojola** [comment]
It should be possible: since dehydrated doesn't appear to have the capability to pass arbitrary arguments to the hook script, would it work to add an environment variable to indicate the nameserver to use for confirmation? 

I'd then just need to figure out how to specify the server to query instead of using the default that `net.LookupTXT` uses.

**Comment by nreilly** [comment]
That could work, but since this script is focused just on linode, wouldn't it make sense to specify it directly? Or more fancily, pull it from the NS records specified in the zone being updated?

**Comment by fomojola** [comment]
Well, checking the local resolver is a proxy for propagation: when I originally set it up I observed a couple of cases where the challenge would fail because the DNS updates hadn't yet propagated. I assumed that if I could see it from a local resolver that Lets Encrypt would also be able to see it: will take a stab at baking in https://github.com/bogdanovich/dns_resolver and then will go from there. Might be a little while before I get to it, though: if you want to send me a pull request will happily merge it.

**Comment by fomojola** [comment]
Commit 634ca2d7609d52291bd67e7f650b7af3bcdab3a4 integrates https://github.com/miekg/dns to let you specify the DNS server to use. Pass the environment variable DEHYDRATED_RESOLVER when you invoke dehydrated and it should use that specific resolver.

**Comment by nreilly** [comment]
First internal certificate deployed! Thanks!
